export const FETCH_AFFICHE_SUCCESS = "FETCH_AFFICHE_SUCCESS"
export const CHANGE_SORT_BY_PRICE_SUCCESS = "CHANGE_SORT_BY_PRICE_SUCCESS"
export const FILTER_DATA_SUCCESS = "FILTER_DATA_SUCCESS"

export const FETCH_FAVORITES_SUCCESS = "FETCH_FAVORITES_SUCCESS"
export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITES_SUCCESS"
export const REMOVE_FAVORITES_SUCCESS = "REMOVE_FAVORITES_SUCCESS"

export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS"

export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS"
export const CLEAR_SEARCH_RESULT_SUCCESS = "CLEAR_SEARCH_RESULT_SUCCESS"
export const FETCH_SEARCH_REQUEST_SUCCESS = "FETCH_SEARCH_REQUEST_SUCCESS"

export const SHOW_SEARCH_DROPDOWN_SUCCESS = "SHOW_SEARCH_DROPDOWN_SUCCESS"
export const HIDE_SEARCH_DROPDOWN_SUCCESS = "HIDE_SEARCH_DROPDOWN_SUCCESS"
export const FETCH_EMPTY_SEARCH_SUCCESS = "FETCH_EMPTY_SEARCH_SUCCESS"